### ISSUE TITLE
Test on BigSur

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-for-mac#106]
In addition, potentially WDA can work instead of this...?

----

We now have an XCTest based driver for newer macOS.
https://github.com/appium/appium-mac2-driver

**Comment by nuno-brio** [comment]
Hi, I am having trouble using AppiumForMac on Big Sur, the method getPageSource() returns empty. Is this a known issue? Thanks.

**Comment by KazuCocoa** [comment]
No, I haven't tested since I did not update my macOS to Big Sur yet.

Thanks for the info. I'm afraid this does not work on the one because of API changes.

**Comment by nuno-brio** [comment]
Another colleague of mine, just tested and it ran smoothly... Maybe it's a problem in my machine or in my code. Will keep you updated on this.

**Comment by nuno-brio** [comment]
Turns out it had something to do with privileges. Had to go to System Preferences->Security & Privacy->Privacy->Accessibility and remove on the minus button, not on the check mark, the access for AppiumForMac and then, add the privileges again when prompted. Tried a few things before getting to this solution, but I guess this did it for me. Thanks for your help!

**Comment by lassebm** [comment]
I'm having issues with AppiumForMac seemingly crashing and misbehaving when automating apps on Big Sur. It seems timing related as behavior is not predictable.

**Comment by KazuCocoa** [comment]
We're going to https://github.com/appium/appium-mac2-driver which works with XCTest base
